const NS='http://www.w3.org/2000/svg';const svg=document.getElementById('sceneSvg');const visualStage=document.getElementById('visualStage');const titleEl=document.getElementById('sceneTitle');const textEl=document.getElementById('sceneText');const kickerEl=document.getElementById('sceneKicker');const statsEl=document.getElementById('sceneStats');const indexEl=document.getElementById('sceneIndex');const totalEl=document.getElementById('sceneTotal');const dotsEl=document.getElementById('dots');const prevBtn=document.getElementById('prevBtn');const nextBtn=document.getElementById('nextBtn');const playBtn=document.getElementById('playBtn');const params=new URLSearchParams(location.search);const captureMode=params.get('capture')==='1';const CAPTURE_FPS=30;const AUTO_MS=6500;let current=0;let timer=null;let captureFrame=0;let captureLastScene=-1;

const scenes=[
{key:'problem',kicker:'01 — المشكلة',title:'الشمس مورد هائل… لكنها عبء على الزراعة',text:'في البيئات الجافة، الإشعاع الشمسي القوي يرفع حرارة سطح التربة ويزيد فقد الماء. المشروع يبدأ من قلب المشكلة: نستخدم الشمس نفسها لصناعة ظل وطاقة وماء للزراعة.',stats:[['1 كم²','مساحة النموذج'],['100 هكتار','أرض قابلة للتخطيط']]},
{key:'tree',kicker:'02 — الشجرة',title:'مظلة شمسية سداسية فوق الأرض',text:'عمود مجوف يحمل مظلة سداسية بقطر 11 م. الكابلات تمر داخل العمود، بينما ترتفع الألواح إلى 5–8 م فوق الأرض. الأرض أسفلها تبقى متاحة للزراعة والحركة.',stats:[['11 م','قطر المظلة'],['5–8 م','الارتفاع'],['~18.4 kWp','قدرة مرجعية/شجرة']]},
{key:'cell',kicker:'03 — الخلية',title:'شجرة في الوسط وست على رؤوس السداسي',text:'خلية D11/S12 تستخدم سداسياً أرضياً ضلعُه 12 م. عند تكرار الخلايا، أشجار الرؤوس تُشارك بين ثلاث خلايا، لذلك تصبح الكثافة الفعلية نحو 80.2 شجرة/هكتار.',stats:[['12 م','ضلع الخلية'],['7 أشجار','الخلية المرئية'],['3 أشجار','النصيب الفعلي/سداسي دوري']]},
{key:'three',kicker:'04 — التحول إلى 3D',title:'نفس الخلية… لكن كبنية حقيقية فوق الأرض',text:'هنا تتحول الخلية السداسية من مخطط ثنائي الأبعاد إلى نموذج ثلاثي الأبعاد: عمود بارتفاع 5 م، قمة عند 8 م، مظلة D11، وست أشجار محيطية على شبكة S12، مع حركة كاميرا ومسار شمسي يوضحان الارتفاع والظل.',stats:[['D11/S12','الهندسة المرجعية'],['7 أشجار','مشهد 3D'],['شمس متحركة','إضاءة وظلال ديناميكية']]},
{key:'scale',kicker:'05 — التوسع',title:'من خلية واحدة إلى شبكة تغطي 1 كم²',text:'بعد فهم الوحدة ثلاثية الأبعاد، يتكرر النمط مثل خلية النحل. في النموذج النظري الدوري، الكثافة تعادل نحو 8,019 شجرة/كم² قبل خصم الطرق والخزانات والمحطات ومناطق الأمان.',stats:[['~8,019','شجرة/كم² نظرياً'],['~65–66%','ظل لحظي صيفاً'],['~9.4 h/m²','متوسط ظل صيفي']]},
{key:'flows',kicker:'06 — الماء والطاقة',title:'الكهرباء تشغّل الماء… والماء يصنع الزراعة',text:'الطاقة تنتقل من الأشجار إلى كتل التجميع ثم المحطة. جزء منها يشغّل الآبار والمضخات، الماء يُخزن ثم يوزع عبر الري بالتنقيط. القياس والتحكم يمران عبر SCADA.',stats:[['~147.5 MWp','قدرة DC مرجعية'],['7,000–8,000 م³','تخزين ماء أولي'],['10 قطاعات','ري/تشغيل مرجعي']]},
{key:'result',kicker:'07 — النتيجة',title:'منظومة زراعية–طاقية بدل محطة شمسية فقط',text:'الهدف هو بقاء معظم الأرض منتجة: الظل فوقها، الطاقة في الهواء، الماء يُضخ ويُدار، والزراعة تعمل تحت شبكة قابلة للتوسع والقياس. نجاح المشروع النهائي يعتمد على الماء والتربة والرياح وتجربة المحاصيل.',stats:[['90–92 ha','هدف زراعة عملي'],['~199–221 GWh/y','إنتاج سنوي أولي'],['Prototype → Pilot → 1 km²','مسار التنفيذ']]}
];

totalEl.textContent=scenes.length;if(captureMode)document.body.dataset.capture='true';

function el(name,attrs={},parent=svg){const node=document.createElementNS(NS,name);Object.entries(attrs).forEach(([k,v])=>node.setAttribute(k,v));parent.appendChild(node);return node}function text(x,y,value,cls='svg-label',anchor='middle'){const n=el('text',{x,y,class:cls,'text-anchor':anchor});n.textContent=value;return n}function clear(){svg.innerHTML=''}function statMarkup(stats){return stats.map(([v,l])=>`<div class="stat"><strong>${v}</strong><span>${l}</span></div>`).join('')}function hexPoints(cx,cy,r){return Array.from({length:6},(_,i)=>{const a=Math.PI/6+i*Math.PI/3;return `${cx+r*Math.cos(a)},${cy+r*Math.sin(a)}`}).join(' ')}function arrow(x1,y1,x2,y2,cls){el('line',{x1,y1,x2,y2,class:cls});const a=Math.atan2(y2-y1,x2-x1),s=12;el('polygon',{points:`${x2},${y2} ${x2-s*Math.cos(a-.5)},${y2-s*Math.sin(a-.5)} ${x2-s*Math.cos(a+.5)},${y2-s*Math.sin(a+.5)}`,class:cls==='energy'?'sun':'tree-dot'})}
function drawTree(cx=600,groundY=535,scale=1){el('ellipse',{cx,cy:groundY+12,rx:165*scale,ry:30*scale,class:'shadow'});el('rect',{x:cx-18*scale,y:groundY-215*scale,width:36*scale,height:215*scale,rx:8,class:'tree-trunk'});const apexY=groundY-355*scale,edgeY=groundY-245*scale,r=175*scale;const pts=Array.from({length:6},(_,i)=>{const a=Math.PI/6+i*Math.PI/3;return [cx+r*Math.cos(a),edgeY+65*scale*Math.sin(a)]});for(let i=0;i<6;i++){const p=pts[i],q=pts[(i+1)%6];el('polygon',{points:`${cx},${apexY} ${p[0]},${p[1]} ${q[0]},${q[1]}`,class:i%2?'panel':'panel-alt'})}el('circle',{cx,cy:apexY,r:7*scale,class:'sun'})}
function drawProblem(){el('rect',{x:0,y:430,width:1200,height:250,class:'ground'});for(let i=0;i<14;i++)el('path',{d:`M ${50+i*85} ${540+(i%3)*20} q 20 -14 40 0 q 20 14 40 0`,class:'dry-line'});el('circle',{cx:945,cy:115,r:54,class:'sun pulse'});for(let i=0;i<7;i++)el('line',{x1:900+i*15,y1:170,x2:760+i*20,y2:410,stroke:'#ffd166','stroke-width':5,opacity:.5});text(110,130,'أرض جافة + إشعاع مرتفع','svg-label','start');text(110,170,'المشكلة ليست نقص الشمس… بل كيفية استخدامها','svg-small','start')}
function drawTreeScene(){el('rect',{x:0,y:535,width:1200,height:145,fill:'#2f6b43'});for(let i=0;i<20;i++)el('line',{x1:80+i*52,y1:570,x2:90+i*52,y2:535,class:'crop'});drawTree();text(600,620,'الألواح فوق الأرض — الزراعة تحتها','svg-label')}
function drawCell(){const cx=600,cy=350,r=205;el('polygon',{points:hexPoints(cx,cy,r),class:'hex'});const pts=[[cx,cy],...Array.from({length:6},(_,i)=>{const a=Math.PI/6+i*Math.PI/3;return [cx+r*Math.cos(a),cy+r*Math.sin(a)]})];pts.forEach(([x,y],i)=>el('circle',{cx:x,cy:y,r:i?16:20,class:'tree-dot pulse'}));text(600,625,'خلية واحدة: شجرة مركزية + 6 أشجار على الرؤوس','svg-label')}
function drawThreeFallback(){const cx=600,cy=350,r=205;el('polygon',{points:hexPoints(cx,cy,r),class:'hex'});text(600,320,'تحميل المشهد ثلاثي الأبعاد…','svg-label');text(600,365,'إذا تعذر WebGL يبقى العرض قابلاً للمتابعة','svg-small')}
function drawScale(){const r=34;for(let row=-5;row<=5;row++){for(let col=-8;col<=8;col++){const x=600+col*r*1.75+(row%2)*r*.875,y=340+row*r*1.52;if(x<70||x>1130||y<80||y>590)continue;el('polygon',{points:hexPoints(x,y,r),class:'hex'});el('circle',{cx:x,cy:y,r:4.5,class:'tree-dot'})}}el('rect',{x:180,y:105,width:840,height:470,fill:'none',stroke:'#74f0a7','stroke-width':4,'stroke-dasharray':'14 10'});text(600,80,'تمثيل بصري لشبكة دورية داخل 1 كم²','svg-label');text(600,625,'الكثافة النظرية ≈ 8,019 شجرة/كم² قبل البنية التحتية','svg-small')}
function drawFlows(){drawTree(250,470,.62);el('rect',{x:0,y:500,width:1200,height:180,fill:'#2f6b43'});el('rect',{x:455,y:330,width:150,height:100,rx:12,class:'station'});text(530,385,'محطة كهرباء','svg-small');el('rect',{x:770,y:235,width:170,height:105,rx:12,class:'tank'});text(855,295,'خزان ماء','svg-small');el('circle',{cx:680,cy:500,r:34,fill:'#152b3d',stroke:'#55c9ff','stroke-width':3});text(680,507,'مضخة','svg-small');arrow(340,330,455,365,'energy');arrow(605,380,680,465,'energy');arrow(680,465,800,330,'water');arrow(855,340,970,490,'water');for(let i=0;i<6;i++)el('line',{x1:940+i*28,y1:535,x2:955+i*28,y2:500,class:'crop'});text(1020,565,'ري بالتنقيط','svg-small');el('rect',{x:455,y:105,width:195,height:90,rx:12,fill:'#10263a',stroke:'#6ee7ff','stroke-width':2});text(552,160,'SCADA','svg-label');arrow(552,195,552,330,'energy')}
function drawResult(){el('rect',{x:0,y:455,width:1200,height:225,fill:'#326f47'});for(let i=0;i<8;i++){const x=130+i*135;drawTree(x,455,.26);for(let j=0;j<4;j++)el('line',{x1:x-45+j*28,y1:520,x2:x-38+j*28,y2:485,class:'crop'})}el('rect',{x:60,y:70,width:1080,height:120,rx:24,fill:'#0d1b2a',stroke:'#27465f','stroke-width':2});text(600,125,'ظل + كهرباء + ماء + زراعة + قياس وتحكم','svg-label');text(600,165,'منظومة واحدة قابلة للتوسع والاختبار','svg-small')}
const drawers={problem:drawProblem,tree:drawTreeScene,cell:drawCell,three:drawThreeFallback,scale:drawScale,flows:drawFlows,result:drawResult};
function render(){const s=scenes[current];clear();kickerEl.textContent=s.kicker;titleEl.textContent=s.title;textEl.textContent=s.text;statsEl.innerHTML=statMarkup(s.stats);indexEl.textContent=current+1;drawers[s.key]();visualStage.dataset.mode=s.key==='three'?'three':'svg';window.dispatchEvent(new CustomEvent('solar-scene-change',{detail:{key:s.key,index:current,captureMode}}));[...dotsEl.children].forEach((d,i)=>d.classList.toggle('active',i===current));prevBtn.disabled=current===0;nextBtn.disabled=current===scenes.length-1}
function go(delta){current=Math.max(0,Math.min(scenes.length-1,current+delta));render()}function buildDots(){scenes.forEach((_,i)=>{const b=document.createElement('button');b.className='dot';b.type='button';b.setAttribute('aria-label',`المشهد ${i+1}`);b.addEventListener('click',()=>{current=i;render()});dotsEl.appendChild(b)})}function stop(){if(timer){clearInterval(timer);timer=null}playBtn.textContent='تشغيل تلقائي';playBtn.setAttribute('aria-pressed','false')}function togglePlay(){if(captureMode)return;if(timer){stop();return}playBtn.textContent='إيقاف';playBtn.setAttribute('aria-pressed','true');timer=setInterval(()=>{current=(current+1)%scenes.length;render()},AUTO_MS)}
prevBtn.addEventListener('click',()=>go(-1));nextBtn.addEventListener('click',()=>go(1));playBtn.addEventListener('click',togglePlay);document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')go(1);if(e.key==='ArrowRight')go(-1);if(e.key==='Escape')stop()});buildDots();render();
if(captureMode){playBtn.textContent='وضع تسجيل 30fps';playBtn.disabled=true;const framesPerScene=Math.round(AUTO_MS/1000*CAPTURE_FPS);function captureTick(){const sceneIndex=Math.floor(captureFrame/framesPerScene)%scenes.length;if(sceneIndex!==captureLastScene){current=sceneIndex;captureLastScene=sceneIndex;render()}captureFrame++;requestAnimationFrame(captureTick)}requestAnimationFrame(captureTick)}
